# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d91da0609346c75b96a1d7e3a7b1aada"
name = "Phuljhadi 2024"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "messoldtech-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
